ALTER TABLE users
ADD COLUMN IF NOT EXISTS password_hash VARCHAR(128),
ADD COLUMN IF NOT EXISTS otp_code_hash VARCHAR(128),
ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS otp_attempts INTEGER NOT NULL DEFAULT 0;
